spring.application.name=gateway
server.port=8080
server.address=0.0.0.0

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.enabled=true

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
# Gateway Routes

# User Service
spring.cloud.gateway.routes[0].id=user-service-route
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

# Delivery Service
spring.cloud.gateway.routes[1].id=delivery-service-route
spring.cloud.gateway.routes[1].uri=lb://DELIVERY-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/delivery/**

# Vehicle Service
spring.cloud.gateway.routes[2].id=vehicle-service-route
spring.cloud.gateway.routes[2].uri=lb://VEHICLE-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/vehicle/**

# Review Service
spring.cloud.gateway.routes[3].id=review-service-route
spring.cloud.gateway.routes[3].uri=lb://REVIEW-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/review/**

# Identity Docs Service
spring.cloud.gateway.routes[4].id=identitydocs-service-route
spring.cloud.gateway.routes[4].uri=lb://IDENTITYDOCS-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/identitydocs/**

# Wallet Service
spring.cloud.gateway.routes[5].id=wallet-service-route
spring.cloud.gateway.routes[5].uri=lb://WALLET-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/wallet/**

# Transaction Service
spring.cloud.gateway.routes[6].id=transaction-service-route
spring.cloud.gateway.routes[6].uri=lb://TRANSACTION-SERVICE
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/transaction/**

# Vehicle Docs Service
spring.cloud.gateway.routes[7].id=vehicledocs-service-route
spring.cloud.gateway.routes[7].uri=lb://VEHICLEDOCS-SERVICE
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/vehicledocs/**

# Tracking Log Service
spring.cloud.gateway.routes[8].id=trackinglog-service-route
spring.cloud.gateway.routes[8].uri=lb://TRACKINGLOG-SERVICE
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/trackinglog/**


spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/unidelivery

management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.health.show-details=always
management.endpoint.gateway.access=read_only
